### ISSUE TITLE
RISC-V toolchain

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#1]
An environment with RISC-V cross-compiler: Dockerfile (preferable) or Vagrant

Should be able to cross-compile helloworld-level .c example

**Comment by sreznick** [comment]
By now I've managed to build toolchain on my Ubuntu 18.04 host and compile some simple C applications like 'hello, world'.

What remains is to dockerize it.

**Comment by AntonKozlov** [comment]
Great, waiting for good news!

**Comment by tsarn** [comment]
Dockerized here: https://github.com/azul-research/jdk-riscv/tree/riscv/dev-riscv/toolchain
