### ISSUE TITLE
Encode `rv_ret` instruction

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#15]

**Comment by AntonKozlov** [comment]
Let it be a macroInstruction (in assmbler for now) that is implemented via some real riscv instruction
```
rv_ret() { mv(pc, lr) }
mv(Register n, Register m) { emit_int32( ... ) }
```

**Comment by tsarn** [comment]
I implemented most of RV64I instructions, but haven't tested them yet. See branch `asm-ret`.

**Comment by AntonKozlov** [comment]
Thanks for sharing the progress! As far as I can see, you mean any test(s) at all. Then it looks more #16 than the issue :) Are you going to proceed to extending the asm or try the freshly encoded instructions for vm_version?
@vasyoid may be interested in this result. Could you sync up and split the works?

@azul-research/riscv I see that `rv` was used to differentiate ppc and riscv instructions. This is relates to #17. Now we have good examples to start work.

**Comment by vasyoid** [comment]
> Then it looks more #16 than the issue :)

Yes, it seems to cover that. I can try implementing some tests for these instructions then.

**Comment by vasyoid** [comment]
@TsarN what else are you planning to do in this issue till the next meeting?

**Comment by tsarn** [comment]
@vasyoid Most likely nothing in the next 24 hours :)

**Comment by vasyoid** [comment]
Fine :) Then I'll try something
