### ISSUE TITLE
Encode instructions

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#16]

**Comment by AntonKozlov** [comment]
This issue is about reading #8 manual and prototyping/implementing instructions encoding. 

It's very desirable to have a general scheme extracted or understood from manual, and the assembler be organized according to the scheme

**Comment by vasyoid** [comment]
Ah, I see the difference now! Thanks.

**Comment by AntonKozlov** [comment]
http://hg.openjdk.java.net/aarch32-port/jdk8u/hotspot/file/90d7b3c8e368/src/cpu/aarch32/vm/assembler_aarch32.hpp

-- source of "inspiration"
