### ISSUE TITLE
vm_version

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#20]

**Comment by AntonKozlov** [comment]
~~http://hg.openjdk.java.net/aarch32-port/jdk8u/hotspot/file/90d7b3c8e368/src/cpu/aarch32/vm/aarch32Test.cpp~~

**Comment by Geckostya** [comment]
What does it mean?

**Comment by AntonKozlov** [comment]
To make vm_version's test pass. It depends on #15 at least

**Comment by vasyoid** [comment]
Somehow I've made it pass vm_version initialization.
Now both release and fastdebug configurations crash in 
`src/hotspot/share/runtime/javaCalls.cpp:439`
when call stub generated in
`StubGenerator::generate_call_stub (src/hotspot/cpu/riscv/stubGenerator_riscv.cpp:79)`
is executed. See [fix-crashes](https://github.com/azul-research/jdk-riscv/tree/fix-crashes) branch.

But I still have some concerns about vm_version.

- Size of RISCV Instructions. RISCV instructions may have variable length, but in
`src/hotspot/cpu/riscv/globalDefinitions_riscv.hpp`
there is a constant `const int BytesPerInstWord`. Which value should it have?
- On ppc functions have [function descriptors](https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/deeply_understand_64_bit_powerpc_elf_abi_function_descriptors?lang=en). I could not find anything similar for risc-v. Can we just leave it?
- ppc also uses a field `static unsigned int _L1_data_cache_line_size`.
Everything I could find about cache line size on risc-v is [this](http://www-inst.eecs.berkeley.edu/~cs250/fa11/handouts/lab3-riscv-v2-icc-pt.pdf) doc. It states that there are two caches -- instruction and data caches, and for both of them cache lines are 64 bytes. Does it describe what we need here?
- ppc supports fast class initialization checks for static methods. I could not find anything about this for risc-v. Is it described anywhere?

**Comment by AntonKozlov** [comment]
> Somehow I've made it pass vm_version initialization.
> Now both release and fastdebug configurations crash in
> `src/hotspot/share/runtime/javaCalls.cpp:439`
> when call stub generated in
> `StubGenerator::generate_call_stub (src/hotspot/cpu/riscv/stubGenerator_riscv.cpp:79)`
> is executed. See [fix-crashes](https://github.com/azul-research/jdk-riscv/tree/fix-crashes) branch.
> 

Great, this unblocks call_stub work (#28). But you've disabled feature detection at all (https://github.com/azul-research/jdk-riscv/commit/59562ed7be396a82113003c1ad61b6b253773ea9#diff-e60d0e936e2ce50fbc07de771144b89dR802) For the purpose of getting usual with assembler, this exercise should be done. Simplest version that detects no features would be good. I like a draft (https://github.com/azul-research/jdk-riscv/commit/59562ed7be396a82113003c1ad61b6b253773ea9#diff-e60d0e936e2ce50fbc07de771144b89dR785), this should be extended and be made to work 

> But I still have some concerns about vm_version.

As a general note, this is riscv-code. You are free to delete and rewrite most part of it. I think that to remove a code (like you did) is a healthy approach. Removed code is always is history or in ppc64 directory nearby. This should be an easy decision for code that we haven't spent any effort on. 

> 
> * Size of RISCV Instructions. RISCV instructions may have variable length, but in
>   `src/hotspot/cpu/riscv/globalDefinitions_riscv.hpp`
>   there is a constant `const int BytesPerInstWord`. Which value should it have?

Probably no value. This is cpu's own value we are free to get rid of. For sake of transparency, a macro that prints a warning when the value is used is possible. Like
```
#define BytePerInstWords ({tty->print_cr("BytePerInstWords %s:%d", __FILE__, __LINE__); -1})
```

> * On ppc functions have [function descriptors](https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/deeply_understand_64_bit_powerpc_elf_abi_function_descriptors?lang=en). I could not find anything similar for risc-v. Can we just leave it?

descriptors are presented in some ABIs of PPC64, but not all of them. Descriptor is like a function pointer, but it's not just address of the first instruction, it have additional context. Like a virtual method of an object should have a `this` to be called. Later ppc64 ABI got rid of descriptors. 

For us, it's dictated by an ABI. Proper way is understand convention on function entry. Or we can just try and see what happens :) I don't expect anything similar in risc-v

> * ppc also uses a field `static unsigned int _L1_data_cache_line_size`.
>   Everything I could find about cache line size on risc-v is [this](http://www-inst.eecs.berkeley.edu/~cs250/fa11/handouts/lab3-riscv-v2-icc-pt.pdf) doc. It states that there are two caches -- instruction and data caches, and for both of them cache lines are 64 bytes. Does it describe what we need here?

Cache size would be interesting when we'll decide how to do cache invalidation,.. AFAIR, ARM32 have recommended implementations provided for such operations. Until then, we can safely avoid remove the field.
PS. The doc seems to describe particular hardware implementation. We would like follow a specification, so our code would work everywhere.

> * ppc supports fast class initialization checks for static methods. I could not find anything about this for risc-v. Is it described anywhere?

Do you mean java class initialization? How it can be, we've copied the ppc code. Or C class initialization? I don't think I understood the topic of this question, could you provide more details?
