### ISSUE TITLE
Atomic::xxx

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#21]
#5 pushed the implementation till the point Atomic::xxx are required.

The implementation seems to be based on section “A” Standard Extension for Atomic Instructions of RISC-V ISA Manual

**Comment by vasyoid** [comment]
Isn't this issue related to #16 ? The asm instructions needed by Atomic::xxx can be implemented first of all.

**Comment by AntonKozlov** [comment]
> Isn't this issue related to #16 ?

Not quite. #16 is about implementing Assembler part, that would be used by all code-generators during jvm run-time. 

This issue is about implementing src/hotspot/os_cpu/linux_riscv/atomic_linux_riscv.hpp, as you correctly identified. The file is implemented by inline asm feature of c compiler. The inline asm is the same static code as the rest part of JVM written in C. They are translated once during jvm (cross)compilation.

**Comment by DmKazakov** [comment]
I have tried to fix atomic_linux_riscv.hpp in https://github.com/azul-research/jdk-riscv/tree/atomic-asm-fix. Not sure if it's succesful, though. Anyway, lines mentioned in #5 don't cause crashes now but it crashes somewhere else.

**Comment by AntonKozlov** [comment]
Could you prepare a Pull Request?
