### ISSUE TITLE
RISC-V Instruction set

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#8]
Find RISC-V 64 bit Instruction set. Link to docs section.

Match the ISA (instruction set architecture) to hotspot's home-grown assembler  https://github.com/azul-research/jdk-riscv/blob/riscv/src/hotspot/cpu/ppc/assembler_ppc.hpp.
Start implementing the asm

**Comment by DmKazakov** [comment]
RISC-V 64 bit Instruction set manual can be found [here](https://riscv.org/specifications/).

**Comment by Geckostya** [comment]
[asm manual](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md) with registers info

**Comment by AntonKozlov** [comment]
Could you add the link to main page?
