### ISSUE TITLE
Calling convention

### ISSUE THREAD

**Issue by AntonKozlov** [azul-research/jdk-riscv#9]
Find calling convention. Understand how C function call works and how they are matched.

Start implementing call_stub https://github.com/azul-research/jdk-riscv/blob/riscv/src/hotspot/cpu/ppc/stubGenerator_ppc.cpp#L79
-- a transformer from C world to Java world. A first step to start executing java code

**Comment by sreznick** [comment]
Understaning of calling convention is documented at wiki: https://github.com/azul-research/jdk-riscv/wiki/RISC-V-calling-convention-summary

**Comment by AntonKozlov** [comment]
Thanks!

Is there any reference links/docs? in case we need to refine some obscure parts

**Comment by Geckostya** [comment]
[asm manual](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md) with registers info

**Comment by AntonKozlov** [comment]
Links would be good to see on main page
